--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-09-13 16:16:40 CDT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 2 (class 3079 OID 16384)
-- Name: adminpack; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS adminpack WITH SCHEMA pg_catalog;


--
-- TOC entry 3617 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION adminpack; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION adminpack IS 'administrative functions for PostgreSQL';


--
-- TOC entry 215 (class 1259 OID 16713)
-- Name: a_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.a_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.a_sequence OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16768)
-- Name: task_list; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_list (
    task_id integer NOT NULL,
    task_description character varying(125) DEFAULT 'no task description'::character varying,
    department_name character varying(60) DEFAULT 'Basic Onboarding'::character varying NOT NULL,
    deadline date NOT NULL,
    confirm_status boolean DEFAULT false NOT NULL,
    confirm_date date,
    employee_name character varying(60),
    member_assigned character varying(60),
    assigned_employee_id integer,
    task_num integer NOT NULL
);


ALTER TABLE public.task_list OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16774)
-- Name: t_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.t_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.t_sequence OWNER TO postgres;

--
-- TOC entry 3618 (class 0 OID 0)
-- Dependencies: 218
-- Name: t_sequence; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.t_sequence OWNED BY public.task_list.task_id;


--
-- TOC entry 220 (class 1259 OID 16836)
-- Name: default_tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.default_tasks (
    task_id integer DEFAULT nextval('public.t_sequence'::regclass) NOT NULL,
    task_description character varying DEFAULT 'no task description'::character varying NOT NULL,
    department character varying,
    deadline character varying NOT NULL,
    member_assigned character varying
);


ALTER TABLE public.default_tasks OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16764)
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    name character varying(30),
    password character varying(30),
    email character varying(30) NOT NULL,
    accountid integer DEFAULT nextval('public.a_sequence'::regclass) NOT NULL,
    account_role character varying(30),
    account_department character varying(60),
    job_title character varying(30),
    start_date date
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16775)
-- Name: task_list_task_num_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_list ALTER COLUMN task_num ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_list_task_num_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 38
    CACHE 1
    CYCLE
);


--
-- TOC entry 3451 (class 2604 OID 24978)
-- Name: task_list task_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_list ALTER COLUMN task_id SET DEFAULT nextval('public.t_sequence'::regclass);


--
-- TOC entry 3611 (class 0 OID 16836)
-- Dependencies: 220
-- Data for Name: default_tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.default_tasks VALUES (2, 'Testing this out more', 'Aidens Onboarding', '2 weeks before hire', 'HR');
INSERT INTO public.default_tasks VALUES (3, 'hi amal', 'Billing', '3 weeks after start', 'HR specialist');
INSERT INTO public.default_tasks VALUES (1, 'Testing this out', 'Aidens Onboarding', '2 days after', 'COO');
INSERT INTO public.default_tasks VALUES (793, 'Trying', 'Basic Onboarding', '3 Months after start', 'Aiden');
INSERT INTO public.default_tasks VALUES (794, 'Trying2', 'Basic Onboarding', '3 Months after start', 'Aiden');
INSERT INTO public.default_tasks VALUES (795, 'Trying3', 'Basic Onboarding', '4 Months after start', 'Aiden2');
INSERT INTO public.default_tasks VALUES (796, 'OneMore', 'Basic Onboarding', '8 Months after start', 'Aiden3');
INSERT INTO public.default_tasks VALUES (274, 'Say hi to Max', 'Basic Onboarding', '1 Months after start', 'COO');
INSERT INTO public.default_tasks VALUES (283, 'Task 9', 'Billing', '1 Months after start', 'coo');


--
-- TOC entry 3607 (class 0 OID 16764)
-- Dependencies: 216
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.employee VALUES ('ben', 'cool', 'bad@yahoo.com', 2, 'Supervisor', 'Basic Onboarding', NULL, NULL);
INSERT INTO public.employee VALUES ('gabe', 'password', 'Great@gmail.com', 1, 'Admin', 'Basic Onboarding', NULL, NULL);
INSERT INTO public.employee VALUES ('tom', 'real', 'tom@gmail.com', 3, 'NewHire', 'Basic Onboarding', NULL, NULL);
INSERT INTO public.employee VALUES ('Gabriel Bentley', 'test123', 'geb190000@utdallas.edu', 4, 'Supervisor', 'Basic Onboarding', NULL, NULL);
INSERT INTO public.employee VALUES ('Garret Starbuck', 'mailFile', 'gabrieledward00@gmail.com', 5, 'NewHire', 'Basic Onboarding', NULL, NULL);
INSERT INTO public.employee VALUES ('Frank Mallard', 'GreatFrank', 'Frank888@utdallas.edu', 6, 'NewHire', 'Basic Onboarding', NULL, NULL);
INSERT INTO public.employee VALUES ('Tushar Wani', NULL, 'junk@gmail.com', 8, 'NewHire', 'Basic Onboarding', 'Boss Man', '1111-11-11');
INSERT INTO public.employee VALUES ('Aiden Escamilla', NULL, 'aiden.escamilla@gmail.com', 9, 'NewHire', 'Billing', 'sadad', '1111-11-11');


--
-- TOC entry 3608 (class 0 OID 16768)
-- Dependencies: 217
-- Data for Name: task_list; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.task_list VALUES (152, 'Update Organizational chart', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 38);
INSERT INTO public.task_list VALUES (143, 'Issues Keycard.', 'Basic Onboarding', '2023-10-10', true, '2023-05-11', 'Gabriel', 'Office Manager', 3, 29);
INSERT INTO public.task_list VALUES (117, 'Submits New User Creation Form to Mednetworx.', 'Basic Onboarding', '2023-09-30', true, '2023-05-11', 'Gabriel', 'Office Manager', 3, 3);
INSERT INTO public.task_list VALUES (139, 'Issues IT equipment and logins.', 'Basic Onboarding', '2023-10-10', true, '2023-09-13', 'Gabriel', 'Office Manager', 3, 25);
INSERT INTO public.task_list VALUES (267, 'Testing this out', 'Aidens Onboarding', '1111-11-09', false, NULL, NULL, 'COO', 8, 1);
INSERT INTO public.task_list VALUES (268, 'Testing this out more', 'Aidens Onboarding', '1111-11-09', false, NULL, NULL, 'HR', 8, 2);
INSERT INTO public.task_list VALUES (269, 'hi amal', 'Billing', '1111-11-08', false, NULL, NULL, 'HR specialist', 8, 3);
INSERT INTO public.task_list VALUES (270, 'Trying', 'Basic Onboarding', '1112-02-11', false, NULL, NULL, 'Aiden', 8, 4);
INSERT INTO public.task_list VALUES (271, 'Trying2', 'Basic Onboarding', '1112-02-11', false, NULL, NULL, 'Aiden', 8, 5);
INSERT INTO public.task_list VALUES (147, 'Add employee information to Employee Information Sheet and Internal Phone List sheet', 'Basic Onboarding', '2023-10-10', true, '2023-09-13', 'Gabriel', 'Office Manager', 3, 33);
INSERT INTO public.task_list VALUES (140, 'Collects Asset/Equipment Agreement.', 'Basic Onboarding', '2023-10-10', true, '2023-05-11', 'Gabriel', 'Office Manager', 3, 26);
INSERT INTO public.task_list VALUES (155, 'Submits New User Creation Form to Mednetworx.', 'Basic Onboarding', '2023-09-30', false, NULL, NULL, 'Office Manager', 5, 3);
INSERT INTO public.task_list VALUES (129, 'Identify Desk.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 3, 15);
INSERT INTO public.task_list VALUES (130, 'Submits New User Creation Form to Mednetworx.', 'Basic Onboarding', '2023-09-30', false, NULL, NULL, 'Department Manager', 3, 16);
INSERT INTO public.task_list VALUES (131, 'Mailboxes.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 3, 17);
INSERT INTO public.task_list VALUES (132, 'Welcome Sign.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 3, 18);
INSERT INTO public.task_list VALUES (133, 'TWC T-shirt.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 3, 19);
INSERT INTO public.task_list VALUES (134, 'Prepares Desk.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 3, 20);
INSERT INTO public.task_list VALUES (135, 'Collect HR documents: Drivers license and Auto Insurance, license, transcripts, CPR, direct deposit.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 21);
INSERT INTO public.task_list VALUES (138, 'E-Verify.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 24);
INSERT INTO public.task_list VALUES (141, 'Order Business Cards.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 27);
INSERT INTO public.task_list VALUES (142, 'Explains 401k.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'COO', 3, 28);
INSERT INTO public.task_list VALUES (144, 'Assign HIPAA and IT Security Courses.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 30);
INSERT INTO public.task_list VALUES (145, 'Insperity portal introduction.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 31);
INSERT INTO public.task_list VALUES (146, 'Add picture and information to check-in iPad', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 32);
INSERT INTO public.task_list VALUES (148, 'Provide TWC t-shirt', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 34);
INSERT INTO public.task_list VALUES (149, 'Complete Favorites form and save in Common Drive', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 35);
INSERT INTO public.task_list VALUES (150, 'Complete Strengths Finder assessment', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 36);
INSERT INTO public.task_list VALUES (151, 'Take picture in TWC shirt - save in Common Drive, print and put on poster', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 3, 37);
INSERT INTO public.task_list VALUES (272, 'Trying3', 'Basic Onboarding', '1112-03-11', false, NULL, NULL, 'Aiden2', 8, 6);
INSERT INTO public.task_list VALUES (156, 'Runs VeriFYI background check.', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Office Manager', 5, 4);
INSERT INTO public.task_list VALUES (157, 'Verifies License.', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Office Manager', 5, 5);
INSERT INTO public.task_list VALUES (158, 'Insider Announcement.', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Office Manager', 5, 6);
INSERT INTO public.task_list VALUES (273, 'OneMore', 'Basic Onboarding', '1112-07-11', false, NULL, NULL, 'Aiden3', 8, 7);
INSERT INTO public.task_list VALUES (160, 'Receives IT Equipment/Checks for readiness', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Office Manager', 5, 8);
INSERT INTO public.task_list VALUES (161, 'Reviews Fingerprinting Results*', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Office Manager', 5, 9);
INSERT INTO public.task_list VALUES (162, 'Updates Organization Chart.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Office Manager', 5, 10);
INSERT INTO public.task_list VALUES (163, 'Creates Keycard(s).', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Office Manager', 5, 11);
INSERT INTO public.task_list VALUES (164, 'Sets up Copy/Printer code.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Office Manager', 5, 12);
INSERT INTO public.task_list VALUES (165, 'Sets up Orientation/Trainings with other departments.', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Department Manager', 5, 13);
INSERT INTO public.task_list VALUES (166, 'Welcome Email with first day instructions.', 'Basic Onboarding', '2023-10-05', false, NULL, NULL, 'COO', 5, 14);
INSERT INTO public.task_list VALUES (167, 'Identify Desk.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 5, 15);
INSERT INTO public.task_list VALUES (168, 'Submits New User Creation Form to Mednetworx.', 'Basic Onboarding', '2023-09-30', false, NULL, NULL, 'Department Manager', 5, 16);
INSERT INTO public.task_list VALUES (169, 'Mailboxes.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 5, 17);
INSERT INTO public.task_list VALUES (170, 'Welcome Sign.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 5, 18);
INSERT INTO public.task_list VALUES (171, 'TWC T-shirt.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 5, 19);
INSERT INTO public.task_list VALUES (172, 'Prepares Desk.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 5, 20);
INSERT INTO public.task_list VALUES (173, 'Collect HR documents: Drivers license and Auto Insurance, license, transcripts, CPR, direct deposit.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 21);
INSERT INTO public.task_list VALUES (174, 'Schedule 30 minutes for Amy Spawn to meet new staff.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 22);
INSERT INTO public.task_list VALUES (175, 'Favorites Form.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 23);
INSERT INTO public.task_list VALUES (176, 'E-Verify.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 24);
INSERT INTO public.task_list VALUES (177, 'Issues IT equipment and logins.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 25);
INSERT INTO public.task_list VALUES (178, 'Collects Asset/Equipment Agreement.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 26);
INSERT INTO public.task_list VALUES (179, 'Order Business Cards.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 27);
INSERT INTO public.task_list VALUES (180, 'Explains 401k.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'COO', 5, 28);
INSERT INTO public.task_list VALUES (275, 'Testing this out', 'Aidens Onboarding', '1111-11-09', false, NULL, NULL, 'COO', 9, 1);
INSERT INTO public.task_list VALUES (276, 'Testing this out more', 'Aidens Onboarding', '1111-11-09', false, NULL, NULL, 'HR', 9, 2);
INSERT INTO public.task_list VALUES (277, 'hi amal', 'Billing', '1111-11-08', false, NULL, NULL, 'HR specialist', 9, 3);
INSERT INTO public.task_list VALUES (278, 'Say hi to Max', 'Basic Onboarding', '1111-12-11', false, NULL, NULL, 'COO', 9, 4);
INSERT INTO public.task_list VALUES (279, 'Trying', 'Basic Onboarding', '1112-02-11', false, NULL, NULL, 'Aiden', 9, 5);
INSERT INTO public.task_list VALUES (280, 'Trying2', 'Basic Onboarding', '1112-02-11', false, NULL, NULL, 'Aiden', 9, 6);
INSERT INTO public.task_list VALUES (154, 'Sends candidate welcome email offer letter, (I-9 and first day paperwork).', 'Basic Onboarding', '2023-09-30', true, '2023-05-11', 'Gabriel', 'COO', 5, 2);
INSERT INTO public.task_list VALUES (281, 'Trying3', 'Basic Onboarding', '1112-03-11', false, NULL, NULL, 'Aiden2', 9, 7);
INSERT INTO public.task_list VALUES (282, 'OneMore', 'Basic Onboarding', '1112-07-11', false, NULL, NULL, 'Aiden3', 9, 8);
INSERT INTO public.task_list VALUES (136, 'Schedule 30 minutes for Amy Spawn to meet new staff.', 'Basic Onboarding', '2023-10-10', true, '2023-09-13', 'Gabriel', 'Office Manager', 3, 22);
INSERT INTO public.task_list VALUES (137, 'Favorites Form.', 'Basic Onboarding', '2023-10-10', true, '2023-09-13', 'Gabriel', 'Office Manager', 3, 23);
INSERT INTO public.task_list VALUES (128, 'Welcome Email with first day instructions.', 'Basic Onboarding', '2023-10-05', false, NULL, NULL, 'COO', 3, 14);
INSERT INTO public.task_list VALUES (181, 'Issues Keycard.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 29);
INSERT INTO public.task_list VALUES (182, 'Assign HIPAA and IT Security Courses.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 30);
INSERT INTO public.task_list VALUES (183, 'Insperity portal introduction.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 31);
INSERT INTO public.task_list VALUES (184, 'Add picture and information to check-in iPad', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 32);
INSERT INTO public.task_list VALUES (185, 'Add employee information to Employee Information Sheet and Internal Phone List sheet', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 33);
INSERT INTO public.task_list VALUES (186, 'Provide TWC t-shirt', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 34);
INSERT INTO public.task_list VALUES (187, 'Complete Favorites form and save in Common Drive', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 35);
INSERT INTO public.task_list VALUES (188, 'Complete Strengths Finder assessment', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 36);
INSERT INTO public.task_list VALUES (189, 'Take picture in TWC shirt - save in Common Drive, print and put on poster', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 37);
INSERT INTO public.task_list VALUES (190, 'Update Organizational chart', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 5, 38);
INSERT INTO public.task_list VALUES (192, 'Sends candidate welcome email offer letter, (I-9 and first day paperwork).', 'Basic Onboarding', '2023-09-30', false, NULL, NULL, 'COO', 6, 2);
INSERT INTO public.task_list VALUES (193, 'Submits New User Creation Form to Mednetworx.', 'Basic Onboarding', '2023-09-30', false, NULL, NULL, 'Office Manager', 6, 3);
INSERT INTO public.task_list VALUES (194, 'Runs VeriFYI background check.', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Office Manager', 6, 4);
INSERT INTO public.task_list VALUES (195, 'Verifies License.', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Office Manager', 6, 5);
INSERT INTO public.task_list VALUES (196, 'Insider Announcement.', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Office Manager', 6, 6);
INSERT INTO public.task_list VALUES (197, 'Request NPI/TPI, SS and DL from new hire', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Office Manager/Billing Director', 6, 7);
INSERT INTO public.task_list VALUES (198, 'Receives IT Equipment/Checks for readiness', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Office Manager', 6, 8);
INSERT INTO public.task_list VALUES (200, 'Updates Organization Chart.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Office Manager', 6, 10);
INSERT INTO public.task_list VALUES (201, 'Creates Keycard(s).', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Office Manager', 6, 11);
INSERT INTO public.task_list VALUES (202, 'Sets up Copy/Printer code.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Office Manager', 6, 12);
INSERT INTO public.task_list VALUES (203, 'Sets up Orientation/Trainings with other departments.', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Department Manager', 6, 13);
INSERT INTO public.task_list VALUES (204, 'Welcome Email with first day instructions.', 'Basic Onboarding', '2023-10-05', false, NULL, NULL, 'COO', 6, 14);
INSERT INTO public.task_list VALUES (205, 'Identify Desk.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 6, 15);
INSERT INTO public.task_list VALUES (206, 'Submits New User Creation Form to Mednetworx.', 'Basic Onboarding', '2023-09-30', false, NULL, NULL, 'Department Manager', 6, 16);
INSERT INTO public.task_list VALUES (207, 'Mailboxes.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 6, 17);
INSERT INTO public.task_list VALUES (208, 'Welcome Sign.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 6, 18);
INSERT INTO public.task_list VALUES (209, 'TWC T-shirt.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 6, 19);
INSERT INTO public.task_list VALUES (210, 'Prepares Desk.', 'Basic Onboarding', '2023-10-09', false, NULL, NULL, 'Department Manager', 6, 20);
INSERT INTO public.task_list VALUES (211, 'Collect HR documents: Drivers license and Auto Insurance, license, transcripts, CPR, direct deposit.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 21);
INSERT INTO public.task_list VALUES (212, 'Schedule 30 minutes for Amy Spawn to meet new staff.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 22);
INSERT INTO public.task_list VALUES (213, 'Favorites Form.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 23);
INSERT INTO public.task_list VALUES (214, 'E-Verify.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 24);
INSERT INTO public.task_list VALUES (215, 'Issues IT equipment and logins.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 25);
INSERT INTO public.task_list VALUES (216, 'Collects Asset/Equipment Agreement.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 26);
INSERT INTO public.task_list VALUES (217, 'Order Business Cards.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 27);
INSERT INTO public.task_list VALUES (218, 'Explains 401k.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'COO', 6, 28);
INSERT INTO public.task_list VALUES (219, 'Issues Keycard.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 29);
INSERT INTO public.task_list VALUES (220, 'Assign HIPAA and IT Security Courses.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 30);
INSERT INTO public.task_list VALUES (221, 'Insperity portal introduction.', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 31);
INSERT INTO public.task_list VALUES (222, 'Add picture and information to check-in iPad', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 32);
INSERT INTO public.task_list VALUES (223, 'Add employee information to Employee Information Sheet and Internal Phone List sheet', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 33);
INSERT INTO public.task_list VALUES (224, 'Provide TWC t-shirt', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 34);
INSERT INTO public.task_list VALUES (225, 'Complete Favorites form and save in Common Drive', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 35);
INSERT INTO public.task_list VALUES (226, 'Complete Strengths Finder assessment', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 36);
INSERT INTO public.task_list VALUES (227, 'Take picture in TWC shirt - save in Common Drive, print and put on poster', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 37);
INSERT INTO public.task_list VALUES (228, 'Update Organizational chart', 'Basic Onboarding', '2023-10-10', false, NULL, NULL, 'Office Manager', 6, 38);
INSERT INTO public.task_list VALUES (126, 'Sets up Copy/Printer code.', 'Basic Onboarding', '2023-10-09', true, '2023-08-13', 'Gabriel', 'Office Manager', 3, 12);
INSERT INTO public.task_list VALUES (127, 'Sets up Orientation/Trainings with other departments.', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Department Manager', 3, 13);
INSERT INTO public.task_list VALUES (199, 'Reviews Fingerprinting Results*', 'Basic Onboarding', '2023-10-09', true, NULL, NULL, 'Office Manager', 6, 9);
INSERT INTO public.task_list VALUES (153, 'Generates Written Offer letter for CEO to sign.', 'Basic Onboarding', '2023-09-26', true, '2023-05-11', 'Gabriel', 'COO', 5, 1);
INSERT INTO public.task_list VALUES (122, 'Receives IT Equipment/Checks for readiness', 'Basic Onboarding', '2023-10-09', true, '2023-05-11', 'Gabriel', 'Office Manager', 3, 8);
INSERT INTO public.task_list VALUES (115, 'Generates Written Offer letter for CEO to sign.', 'Basic Onboarding', '2023-09-26', true, '2023-05-11', 'Gabriel', 'COO', 3, 1);
INSERT INTO public.task_list VALUES (124, 'Updates Organization Chart.', 'Basic Onboarding', '2023-10-09', true, '2023-05-22', 'Gabriel', 'Office Manager', 3, 10);
INSERT INTO public.task_list VALUES (125, 'Creates Keycard(s).', 'Basic Onboarding', '2023-10-09', true, '2023-05-22', 'Gabriel', 'Office Manager', 3, 11);
INSERT INTO public.task_list VALUES (191, 'Generates Written Offer letter for CEO to sign.', 'Basic Onboarding', '2023-09-26', true, '2023-09-13', 'Gabriel', 'COO', 6, 1);
INSERT INTO public.task_list VALUES (159, 'Request NPI/TPI, SS and DL from new hire', 'Basic Onboarding', '2023-10-03', false, NULL, NULL, 'Office Manager/Billing Director', 5, 7);
INSERT INTO public.task_list VALUES (116, 'Sends candidate welcome email offer letter, (I-9 and first day paperwork).', 'Basic Onboarding', '2023-09-30', true, '2023-05-11', 'Gabriel', 'COO', 3, 2);
INSERT INTO public.task_list VALUES (118, 'Runs VeriFYI background check.', 'Basic Onboarding', '2023-10-03', true, '2023-05-11', 'Gabriel', 'Office Manager', 3, 4);
INSERT INTO public.task_list VALUES (119, 'Verifies License.', 'Basic Onboarding', '2023-10-03', true, '2023-05-11', 'Gabriel', 'Office Manager', 3, 5);
INSERT INTO public.task_list VALUES (120, 'Insider Announcement.', 'Basic Onboarding', '2023-10-03', true, '2023-05-11', 'Gabriel', 'Office Manager', 3, 6);
INSERT INTO public.task_list VALUES (123, 'Reviews Fingerprinting Results*', 'Basic Onboarding', '2023-10-09', true, '2023-05-11', 'Gabriel', 'Office Manager', 3, 9);
INSERT INTO public.task_list VALUES (121, 'Request NPI/TPI, SS and DL from new hire', 'Basic Onboarding', '2023-10-03', true, '2023-05-11', 'Gabriel', 'Office Manager/Billing Director', 3, 7);


--
-- TOC entry 3619 (class 0 OID 0)
-- Dependencies: 215
-- Name: a_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.a_sequence', 9, true);


--
-- TOC entry 3620 (class 0 OID 0)
-- Dependencies: 218
-- Name: t_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.t_sequence', 283, true);


--
-- TOC entry 3621 (class 0 OID 0)
-- Dependencies: 219
-- Name: task_list_task_num_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_list_task_num_seq', 38, true);


--
-- TOC entry 3458 (class 2606 OID 16778)
-- Name: employee accountID_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT "accountID_pkey" PRIMARY KEY (accountid);


--
-- TOC entry 3462 (class 2606 OID 16843)
-- Name: default_tasks default_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.default_tasks
    ADD CONSTRAINT default_tasks_pkey PRIMARY KEY (task_id);


--
-- TOC entry 3460 (class 2606 OID 16780)
-- Name: task_list task_list_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_list
    ADD CONSTRAINT task_list_pkey PRIMARY KEY (task_id);


--
-- TOC entry 3463 (class 2606 OID 16844)
-- Name: task_list employee_foreign_key; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_list
    ADD CONSTRAINT employee_foreign_key FOREIGN KEY (assigned_employee_id) REFERENCES public.employee(accountid) ON DELETE CASCADE;


-- Completed on 2023-09-13 16:16:40 CDT

--
-- PostgreSQL database dump complete
--

