services:
  warren-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5005:5432'
    volumes:
      - warren-db:/var/lib/postgresql/data

  # Normally will be using `npx prisma migrate dev` to load the schema now. No defaultDB file to load.
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
volumes:
  warren-db:
    driver: local