--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

-- Started on 2022-11-28 15:50:03 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3600 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- TOC entry 214 (class 1259 OID 16462)
-- Name: a_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.a_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.a_sequence OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 212 (class 1259 OID 16439)
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    name character varying(30),
    password character varying(30),
    email character varying(30) NOT NULL,
    accountid integer DEFAULT nextval('public.a_sequence'::regclass) NOT NULL,
    account_role character varying(30),
    account_department character varying(60)
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16445)
-- Name: task_list; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_list (
    task_id integer NOT NULL,
    task_description character varying(125) DEFAULT 'no task description'::character varying,
    department_name character varying(60) DEFAULT 'Basic Onboarding'::character varying NOT NULL,
    deadline date NOT NULL,
    confirm_status boolean DEFAULT false NOT NULL,
    confirm_date date,
    employee_name character varying(60),
    member_assigned character varying(60),
    assigned_employee_id integer,
    task_num integer NOT NULL
);


ALTER TABLE public.task_list OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16464)
-- Name: t_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.t_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.t_sequence OWNER TO postgres;

--
-- TOC entry 3601 (class 0 OID 0)
-- Dependencies: 215
-- Name: t_sequence; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.t_sequence OWNED BY public.task_list.task_id;


--
-- TOC entry 216 (class 1259 OID 16472)
-- Name: task_list_task_num_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_list ALTER COLUMN task_num ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_list_task_num_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 38
    CACHE 1
    CYCLE
);


--
-- TOC entry 3445 (class 2604 OID 16465)
-- Name: task_list task_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_list ALTER COLUMN task_id SET DEFAULT nextval('public.t_sequence'::regclass);


--
-- TOC entry 3590 (class 0 OID 16439)
-- Dependencies: 212
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee (name, password, email, accountid, account_role, account_department) FROM stdin;
ben	cool	bad@yahoo.com	2	Supervisor	Basic Onboarding
gabe	password	Great@gmail.com	1	Admin	Basic Onboarding
tom	real	tom@gmail.com	3	NewHire	Basic Onboarding
Gabriel Bentley	test123	geb190000@utdallas.edu	4	Supervisor	Basic Onboarding
Garret Starbuck	mailFile	gabrieledward00@gmail.com	5	NewHire	Basic Onboarding
Frank Mallard	GreatFrank	Frank888@utdallas.edu	6	NewHire	Basic Onboarding
Test Man	difDepartment	test8430@gmail.com	7	NewHire	Management
\.


--
-- TOC entry 3591 (class 0 OID 16445)
-- Dependencies: 213
-- Data for Name: task_list; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_list (task_id, task_description, department_name, deadline, confirm_status, confirm_date, employee_name, member_assigned, assigned_employee_id, task_num) FROM stdin;
115	Generates Written Offer letter for CEO to sign.	Basic Onboarding	2023-09-26	f	\N	\N	COO	3	1
116	Sends candidate welcome email offer letter, (I-9 and first day paperwork).	Basic Onboarding	2023-09-30	f	\N	\N	COO	3	2
117	Submits New User Creation Form to Mednetworx.	Basic Onboarding	2023-09-30	f	\N	\N	Office Manager	3	3
118	Runs VeriFYI background check.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	3	4
119	Verifies License.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	3	5
120	Insider Announcement.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	3	6
121	Request NPI/TPI, SS and DL from new hire	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager/Billing Director	3	7
122	Receives IT Equipment/Checks for readiness	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	3	8
123	Reviews Fingerprinting Results*	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	3	9
124	Updates Organization Chart.	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	3	10
125	Creates Keycard(s).	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	3	11
126	Sets up Copy/Printer code.	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	3	12
127	Sets up Orientation/Trainings with other departments.	Basic Onboarding	2023-10-03	f	\N	\N	Department Manager	3	13
128	Welcome Email with first day instructions.	Basic Onboarding	2023-10-05	f	\N	\N	COO	3	14
129	Identify Desk.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	3	15
130	Submits New User Creation Form to Mednetworx.	Basic Onboarding	2023-09-30	f	\N	\N	Department Manager	3	16
131	Mailboxes.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	3	17
132	Welcome Sign.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	3	18
133	TWC T-shirt.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	3	19
134	Prepares Desk.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	3	20
135	Collect HR documents: Drivers license and Auto Insurance, license, transcripts, CPR, direct deposit.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	21
136	Schedule 30 minutes for Amy Spawn to meet new staff.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	22
137	Favorites Form.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	23
138	E-Verify.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	24
139	Issues IT equipment and logins.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	25
140	Collects Asset/Equipment Agreement.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	26
141	Order Business Cards.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	27
142	Explains 401k.	Basic Onboarding	2023-10-10	f	\N	\N	COO	3	28
143	Issues Keycard.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	29
144	Assign HIPAA and IT Security Courses.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	30
145	Insperity portal introduction.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	31
146	Add picture and information to check-in iPad	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	32
147	Add employee information to Employee Information Sheet and Internal Phone List sheet	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	33
148	Provide TWC t-shirt	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	34
149	Complete Favorites form and save in Common Drive	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	35
150	Complete Strengths Finder assessment	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	36
151	Take picture in TWC shirt - save in Common Drive, print and put on poster	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	37
152	Update Organizational chart	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	3	38
153	Generates Written Offer letter for CEO to sign.	Basic Onboarding	2023-09-26	f	\N	\N	COO	5	1
154	Sends candidate welcome email offer letter, (I-9 and first day paperwork).	Basic Onboarding	2023-09-30	f	\N	\N	COO	5	2
155	Submits New User Creation Form to Mednetworx.	Basic Onboarding	2023-09-30	f	\N	\N	Office Manager	5	3
156	Runs VeriFYI background check.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	5	4
157	Verifies License.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	5	5
158	Insider Announcement.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	5	6
159	Request NPI/TPI, SS and DL from new hire	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager/Billing Director	5	7
160	Receives IT Equipment/Checks for readiness	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	5	8
161	Reviews Fingerprinting Results*	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	5	9
162	Updates Organization Chart.	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	5	10
163	Creates Keycard(s).	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	5	11
164	Sets up Copy/Printer code.	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	5	12
165	Sets up Orientation/Trainings with other departments.	Basic Onboarding	2023-10-03	f	\N	\N	Department Manager	5	13
166	Welcome Email with first day instructions.	Basic Onboarding	2023-10-05	f	\N	\N	COO	5	14
167	Identify Desk.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	5	15
168	Submits New User Creation Form to Mednetworx.	Basic Onboarding	2023-09-30	f	\N	\N	Department Manager	5	16
169	Mailboxes.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	5	17
170	Welcome Sign.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	5	18
171	TWC T-shirt.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	5	19
172	Prepares Desk.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	5	20
173	Collect HR documents: Drivers license and Auto Insurance, license, transcripts, CPR, direct deposit.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	21
174	Schedule 30 minutes for Amy Spawn to meet new staff.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	22
175	Favorites Form.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	23
176	E-Verify.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	24
177	Issues IT equipment and logins.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	25
178	Collects Asset/Equipment Agreement.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	26
179	Order Business Cards.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	27
180	Explains 401k.	Basic Onboarding	2023-10-10	f	\N	\N	COO	5	28
181	Issues Keycard.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	29
182	Assign HIPAA and IT Security Courses.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	30
183	Insperity portal introduction.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	31
184	Add picture and information to check-in iPad	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	32
185	Add employee information to Employee Information Sheet and Internal Phone List sheet	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	33
186	Provide TWC t-shirt	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	34
187	Complete Favorites form and save in Common Drive	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	35
188	Complete Strengths Finder assessment	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	36
189	Take picture in TWC shirt - save in Common Drive, print and put on poster	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	37
190	Update Organizational chart	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	5	38
191	Generates Written Offer letter for CEO to sign.	Basic Onboarding	2023-09-26	f	\N	\N	COO	6	1
192	Sends candidate welcome email offer letter, (I-9 and first day paperwork).	Basic Onboarding	2023-09-30	f	\N	\N	COO	6	2
193	Submits New User Creation Form to Mednetworx.	Basic Onboarding	2023-09-30	f	\N	\N	Office Manager	6	3
194	Runs VeriFYI background check.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	6	4
195	Verifies License.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	6	5
196	Insider Announcement.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	6	6
197	Request NPI/TPI, SS and DL from new hire	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager/Billing Director	6	7
198	Receives IT Equipment/Checks for readiness	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	6	8
199	Reviews Fingerprinting Results*	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	6	9
200	Updates Organization Chart.	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	6	10
201	Creates Keycard(s).	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	6	11
202	Sets up Copy/Printer code.	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	6	12
203	Sets up Orientation/Trainings with other departments.	Basic Onboarding	2023-10-03	f	\N	\N	Department Manager	6	13
204	Welcome Email with first day instructions.	Basic Onboarding	2023-10-05	f	\N	\N	COO	6	14
205	Identify Desk.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	6	15
206	Submits New User Creation Form to Mednetworx.	Basic Onboarding	2023-09-30	f	\N	\N	Department Manager	6	16
207	Mailboxes.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	6	17
208	Welcome Sign.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	6	18
209	TWC T-shirt.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	6	19
210	Prepares Desk.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	6	20
211	Collect HR documents: Drivers license and Auto Insurance, license, transcripts, CPR, direct deposit.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	21
212	Schedule 30 minutes for Amy Spawn to meet new staff.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	22
213	Favorites Form.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	23
214	E-Verify.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	24
215	Issues IT equipment and logins.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	25
216	Collects Asset/Equipment Agreement.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	26
217	Order Business Cards.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	27
218	Explains 401k.	Basic Onboarding	2023-10-10	f	\N	\N	COO	6	28
219	Issues Keycard.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	29
220	Assign HIPAA and IT Security Courses.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	30
221	Insperity portal introduction.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	31
222	Add picture and information to check-in iPad	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	32
223	Add employee information to Employee Information Sheet and Internal Phone List sheet	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	33
224	Provide TWC t-shirt	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	34
225	Complete Favorites form and save in Common Drive	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	35
226	Complete Strengths Finder assessment	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	36
227	Take picture in TWC shirt - save in Common Drive, print and put on poster	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	37
228	Update Organizational chart	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	6	38
229	Generates Written Offer letter for CEO to sign.	Basic Onboarding	2023-09-26	f	\N	\N	COO	7	1
230	Sends candidate welcome email offer letter, (I-9 and first day paperwork).	Basic Onboarding	2023-09-30	f	\N	\N	COO	7	2
231	Submits New User Creation Form to Mednetworx.	Basic Onboarding	2023-09-30	f	\N	\N	Office Manager	7	3
232	Runs VeriFYI background check.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	7	4
233	Verifies License.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	7	5
234	Insider Announcement.	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager	7	6
235	Request NPI/TPI, SS and DL from new hire	Basic Onboarding	2023-10-03	f	\N	\N	Office Manager/Billing Director	7	7
236	Receives IT Equipment/Checks for readiness	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	7	8
237	Reviews Fingerprinting Results*	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	7	9
238	Updates Organization Chart.	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	7	10
239	Creates Keycard(s).	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	7	11
240	Sets up Copy/Printer code.	Basic Onboarding	2023-10-09	f	\N	\N	Office Manager	7	12
241	Sets up Orientation/Trainings with other departments.	Basic Onboarding	2023-10-03	f	\N	\N	Department Manager	7	13
242	Welcome Email with first day instructions.	Basic Onboarding	2023-10-05	f	\N	\N	COO	7	14
243	Identify Desk.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	7	15
244	Submits New User Creation Form to Mednetworx.	Basic Onboarding	2023-09-30	f	\N	\N	Department Manager	7	16
245	Mailboxes.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	7	17
246	Welcome Sign.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	7	18
247	TWC T-shirt.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	7	19
248	Prepares Desk.	Basic Onboarding	2023-10-09	f	\N	\N	Department Manager	7	20
249	Collect HR documents: Drivers license and Auto Insurance, license, transcripts, CPR, direct deposit.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	21
250	Schedule 30 minutes for Amy Spawn to meet new staff.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	22
251	Favorites Form.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	23
252	E-Verify.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	24
253	Issues IT equipment and logins.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	25
254	Collects Asset/Equipment Agreement.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	26
255	Order Business Cards.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	27
256	Explains 401k.	Basic Onboarding	2023-10-10	f	\N	\N	COO	7	28
257	Issues Keycard.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	29
258	Assign HIPAA and IT Security Courses.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	30
259	Insperity portal introduction.	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	31
260	Add picture and information to check-in iPad	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	32
261	Add employee information to Employee Information Sheet and Internal Phone List sheet	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	33
262	Provide TWC t-shirt	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	34
263	Complete Favorites form and save in Common Drive	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	35
264	Complete Strengths Finder assessment	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	36
265	Take picture in TWC shirt - save in Common Drive, print and put on poster	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	37
266	Update Organizational chart	Basic Onboarding	2023-10-10	f	\N	\N	Office Manager	7	38
\.


--
-- TOC entry 3602 (class 0 OID 0)
-- Dependencies: 214
-- Name: a_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.a_sequence', 7, true);


--
-- TOC entry 3603 (class 0 OID 0)
-- Dependencies: 215
-- Name: t_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.t_sequence', 266, true);


--
-- TOC entry 3604 (class 0 OID 0)
-- Dependencies: 216
-- Name: task_list_task_num_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_list_task_num_seq', 38, true);


--
-- TOC entry 3447 (class 2606 OID 16461)
-- Name: employee accountID_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT "accountID_pkey" PRIMARY KEY (accountid);


--
-- TOC entry 3449 (class 2606 OID 16452)
-- Name: task_list task_list_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_list
    ADD CONSTRAINT task_list_pkey PRIMARY KEY (task_id);


--
-- TOC entry 3450 (class 2606 OID 16466)
-- Name: task_list employee_foreign_key; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_list
    ADD CONSTRAINT employee_foreign_key FOREIGN KEY (assigned_employee_id) REFERENCES public.employee(accountid) NOT VALID;


-- Completed on 2022-11-28 15:50:03 CST

--
-- PostgreSQL database dump complete
--

