//client side part of the qr code
import QRCode from "qrcode"
import {useState} from 'react'
import Head from 'next/head'
function QrCodePage() {
  const [username, setUsername] = useState('')
  const [src, setSrc] = useState('')
  const generate = () =>{
    //add the url for the qr code to go to
    QRCode.toDataURL(`https://example.com/${username}`).then(setSrc).catch((err) => {
      console.error(err); 
    });
  }
  return (
    <div>
      <Head>
        <title>QR Code Page</title>
        <meta name = 'description' content ='Generated by qr-code-page'/>
        <link rel = 'icon' href = '/favicon.ico'/>
      </Head>
      <input
      className = 'bg-black text-white'
      type = 'text'
      value = {username}
      onChange = {(e) => setUsername(e.target.value)}/>
      <img src={src}/>
    <button type='button' onClick={generate}>Create QR Code</button>
    </div> 
  )
}

export default QrCodePage
